name: Workflow Commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting error with params
        run: echo "::error title:Error title,file=Vehicle.java,line=3,endLine=3,col=5,endColumn=7::Missing Selicolon"
      - name: Setting debug with params
        run: echo "::debug title:Debug title,file=Vehicle.java,line=3,endLine=3,col=5,endColumn=7::Missing Selicolon"
      - name: Setting warning with params
        run: echo "::warning title:Warning title,file=Vehicle.java,line=3,endLine=3,col=5,endColumn=7::Missing Selicolon"
      - name: Setting notice with params
        run: echo "::notice title:Notice title,file=Vehicle.java,line=3,endLine=3,col=5,endColumn=7::Missing Selicolon"